### ISSUE TITLE
dv_upload_manifest can choke on windows line endings

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dataverse_utils#14]
dataverse_utils.py line 551 can choke on the dictionary key because windows can add extra line endings doing things like changing 'tag' to 'tag\r'.  This should be an easy fix, but may be better repaired further upstream by ensuring that all files are read with `newline=''` and/or that the ends of lines are stripped of excess whitespace.

**Comment by Kashirigi** [comment]
Fixed but forgot to update this ticket

**Comment by plesubc** [comment]
Fixed but forgot to update ths ticket
